### ISSUE TITLE
Callback never called on iOS

### ISSUE THREAD

**Issue by pboulch** [hypery2k/nativescript-urlhandler#77] opened 2018-09-17 14:56 UTC
Hi ! I tried to use this plugin for my deep links. On ANdroid no problem, it's work. But on iOS the callback is never called. I followed the instructions : change Info.plist, call handleOpenURL into the app.component.ts (into ngOnInit). 

Did I miss something ?

**Comment by hypery2k** [comment] 2018-09-17 16:09
would be great if you tell more about your setup, version info and other plugins used etc.

**Comment by pboulch** [comment] 2018-09-18 09:27
Ok, I found the problem. I use the WonderPush plugin, and, with iOS, it override the delegate.

**Comment by hypery2k** [comment] 2018-09-18 09:47
ok, so it's a duplicate of #24

**Closed** 2018-09-18 09:47 UTC
Labels: bug, duplicate, platform:ios
